image: docker:latest

services:
  - docker:dind

stages:
  - deploy

deploy:
  tags:
    - prod
  stage: deploy
  script:
    - cp -r .env.testing .env
    - docker image prune -f
    - docker-compose -f "docker-compose.testing.yml" up --build -d